#pragma once
#ifndef IB_HIJACK_EXPORT
#include "../Default.h"
#endif

#define IB_HIJACK_DLL "srvcli.dll"
#define IB_HIJACK_DLL_NOEXT "srvcli"
#define IB_HIJACK_DLL_DIR "C:\\Windows\\System32"
#define IB_HIJACK_DLL_DESC "Server Service Client DLL"

IB_HIJACK_EXPORT(1, I_NetDfsGetVersion)
IB_HIJACK_EXPORT(2, I_NetServerSetServiceBits)
IB_HIJACK_EXPORT(3, I_NetServerSetServiceBitsEx)
IB_HIJACK_EXPORT(4, LocalAliasGet)
IB_HIJACK_EXPORT(5, LocalFileClose)
IB_HIJACK_EXPORT(6, LocalFileEnum)
IB_HIJACK_EXPORT(7, LocalFileEnumEx)
IB_HIJACK_EXPORT(8, LocalFileGetInfo)
IB_HIJACK_EXPORT(9, LocalFileGetInfoEx)
IB_HIJACK_EXPORT(10, LocalServerCertificateMappingAdd)
IB_HIJACK_EXPORT(11, LocalServerCertificateMappingEnum)
IB_HIJACK_EXPORT(12, LocalServerCertificateMappingGet)
IB_HIJACK_EXPORT(13, LocalServerCertificateMappingRemove)
IB_HIJACK_EXPORT(14, LocalSessionDel)
IB_HIJACK_EXPORT(15, LocalSessionEnum)
IB_HIJACK_EXPORT(16, LocalSessionEnumEx)
IB_HIJACK_EXPORT(17, LocalSessionGetInfo)
IB_HIJACK_EXPORT(18, LocalSessionGetInfoEx)
IB_HIJACK_EXPORT(19, LocalShareAdd)
IB_HIJACK_EXPORT(20, LocalShareDelEx)
IB_HIJACK_EXPORT(21, LocalShareEnum)
IB_HIJACK_EXPORT(22, LocalShareEnumEx)
IB_HIJACK_EXPORT(23, LocalShareGetInfo)
IB_HIJACK_EXPORT(24, LocalShareGetInfoEx)
IB_HIJACK_EXPORT(25, LocalShareSetInfo)
IB_HIJACK_EXPORT(26, NetConnectionEnum)
IB_HIJACK_EXPORT(27, NetFileClose)
IB_HIJACK_EXPORT(28, NetFileEnum)
IB_HIJACK_EXPORT(29, NetFileGetInfo)
IB_HIJACK_EXPORT(30, NetRemoteTOD)
IB_HIJACK_EXPORT(31, NetServerAliasAdd)
IB_HIJACK_EXPORT(32, NetServerAliasDel)
IB_HIJACK_EXPORT(33, NetServerAliasEnum)
IB_HIJACK_EXPORT(34, NetServerComputerNameAdd)
IB_HIJACK_EXPORT(35, NetServerComputerNameDel)
IB_HIJACK_EXPORT(36, NetServerDiskEnum)
IB_HIJACK_EXPORT(37, NetServerGetInfo)
IB_HIJACK_EXPORT(38, NetServerSetInfo)
IB_HIJACK_EXPORT(39, NetServerStatisticsGet)
IB_HIJACK_EXPORT(40, NetServerTransportAdd)
IB_HIJACK_EXPORT(41, NetServerTransportAddEx)
IB_HIJACK_EXPORT(42, NetServerTransportDel)
IB_HIJACK_EXPORT(43, NetServerTransportEnum)
IB_HIJACK_EXPORT(44, NetSessionDel)
IB_HIJACK_EXPORT(45, NetSessionEnum)
IB_HIJACK_EXPORT(46, NetSessionGetInfo)
IB_HIJACK_EXPORT(47, NetShareAdd)
IB_HIJACK_EXPORT(48, NetShareCheck)
IB_HIJACK_EXPORT(49, NetShareDel)
IB_HIJACK_EXPORT(50, NetShareDelEx)
IB_HIJACK_EXPORT(51, NetShareDelSticky)
IB_HIJACK_EXPORT(52, NetShareEnum)
IB_HIJACK_EXPORT(53, NetShareEnumSticky)
IB_HIJACK_EXPORT(54, NetShareGetInfo)
IB_HIJACK_EXPORT(55, NetShareSetInfo)
IB_HIJACK_EXPORT(56, NetpsNameCanonicalize)
IB_HIJACK_EXPORT(57, NetpsNameCompare)
IB_HIJACK_EXPORT(58, NetpsNameValidate)
IB_HIJACK_EXPORT(59, NetpsPathCanonicalize)
IB_HIJACK_EXPORT(60, NetpsPathCompare)
IB_HIJACK_EXPORT(61, NetpsPathType)